language: ruby
cache: bundler
rvm: 2.3.3
bundler_args: "--without production development"
services: postgresql

env:
  - COMMAND="rake test:units"
  - COMMAND="rake test:others"
  - COMMAND="rubocop -D -f simple"
  - COMMAND="haml-lint --exclude-linter LineLength app/views"
  - COMMAND="scss-lint app/assets/stylesheets"
  - COMMAND="eslint app/assets/javascripts"
matrix:
  include:
    - env: COMMAND="rake test:functionals"
      addons:
        apt:
          packages: texlive-latex-base
  allow_failures:
    - env: COMMAND="haml-lint --exclude-linter LineLength app/views"
    - env: COMMAND="scss-lint app/assets/stylesheets"
    - env: COMMAND="eslint app/assets/javascripts"
    - env: COMMAND="brakeman"

before_script:
- psql -c 'create database kontes_terbuka_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- cp .env.default .env
script:
  - "bundle exec $COMMAND"
after_script:
- bundle exec haml-lint --exclude-linter LineLength app/views
- bundle exec scss-lint app/assets/stylesheets
- bundle exec eslint app/assets/javascripts
