# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
          #POSTGRES_USER: myapp
          #POSTGRES_DB: myapp_test
          #POSTGRES_PASSWORD: ""
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.0
      #    bundler-cache: true
      - run: | 
          bundle install --without production development
      - name: Build and run tests
        env:
          #DATABASE_URL: postgres://postgres:@localhost:5432/test
          #RAILS_ENV: test
          RAILS_ENV: test
          PGHOST: localhost
          PGPASSWORD : postgres
        #  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          psql -c 'create database kontes_terbuka_test;' -U postgres
          cp config/database.yml.travis config/database.yml
          cp .env.default .env
          bundle exec rake db:setup
          bundle exec rake test:units || true 
          bundle exec rake test:others
          sudo apt-get install texlive-latex-base
          bundle exec rake test:functionals || true
  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.0
      - name: Run haml-lint
        run: |
          bundle exec haml-lint --exclude-linter LineLength app/views || true
      - name: Run scss-lint
        run: |
          bundle exec scss-lint app/assets/stylesheets || true
      - name: Run eslint
        run: |
          bundle exec eslint app/assets/javascripts || true
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.0
      - run: | 
          bundle install --without production development
      - name: Run rubocop
        run: |
          rubocop -a
  brakeman:
    name: brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.0
      - name: Run brakeman
        run: |
          bundle exec brakeman || true
  traceroute:
    name: traceroute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.0
      - name: Run traceroute
        run: |
          bundle exec rake traceroute FAIL_ON_ERROR=1 || true
